version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend22:
    build: .
    container_name: backend_app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/postgres"
    # Uncomment below if you want to bind-mount your code for live reloads
    # volumes:
    #   - .:/app
    #   - /app/node_modules

volumes:
  postgres_data: